# Generated by Django 3.2.3 on 2021-06-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210605_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_1',
            field=models.ImageField(upload_to='blog_img'),
        ),
    ]
