# Generated by Django 3.2.3 on 2021-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210529_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='fb_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ig_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='org_img'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tw_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='yt_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
