# Generated by Django 3.2.3 on 2021-06-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210529_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mail',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
