# Generated by Django 3.2.3 on 2021-06-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='img_1',
            field=models.ImageField(blank=True, default='', upload_to='pet_img'),
        ),
        migrations.AddField(
            model_name='pet',
            name='img_2',
            field=models.ImageField(blank=True, default='', upload_to='pet_img'),
        ),
        migrations.AddField(
            model_name='pet',
            name='img_3',
            field=models.ImageField(blank=True, default='', upload_to='pet_img'),
        ),
        migrations.AddField(
            model_name='pet',
            name='img_4',
            field=models.ImageField(blank=True, default='', upload_to='pet_img'),
        ),
    ]
